# Generated by Django 5.0.3 on 2024-03-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id_estudante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_estudante', models.OneToOneField(db_column='id_estudante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='estudante.estudante')),
                ('curso', models.IntegerField()),
                ('anolectivo', models.CharField(max_length=255)),
                ('uc', models.CharField(max_length=255)),
                ('classificacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nota',
                'managed': False,
            },
        ),
    ]
