# Generated by Django 5.0.3 on 2024-04-06 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamento',
            fields=[
                ('id_alojamento', models.AutoField(primary_key=True, serialize=False)),
                ('renda_base', models.FloatField()),
                ('nquartos', models.IntegerField()),
                ('aluguerparcial', models.CharField(max_length=255)),
                ('nquartoslivres', models.IntegerField()),
            ],
            options={
                'db_table': 'alojamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id_estudante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoServ',
            fields=[
                ('id_senhorio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo', models.IntegerField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('mensalidade', models.IntegerField()),
            ],
            options={
                'db_table': 'contrato_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id_desconto', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'desconto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id_prestador', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prestador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Senhorio',
            fields=[
                ('id_senhorio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'senhorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aluguer',
            fields=[
                ('id_estudante', models.OneToOneField(db_column='id_estudante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='techaconchego.estudante')),
                ('id_senhorio', models.IntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('renda_final', models.IntegerField()),
            ],
            options={
                'db_table': 'aluguer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_estudante', models.OneToOneField(db_column='id_estudante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='techaconchego.estudante')),
                ('curso', models.IntegerField()),
                ('anolectivo', models.CharField(max_length=255)),
                ('uc', models.CharField(max_length=255)),
                ('classificacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nota',
                'managed': False,
            },
        ),
    ]
