# Generated by Django 5.0.3 on 2024-04-16 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techaconchego', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alojamento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='aluguer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contratoserv',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='desconto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estudante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prestador',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='senhorio',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_landlord', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
