# Generated by Django 5.0.3 on 2024-03-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senhorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id_estudante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('id_desconto', models.ForeignKey(blank=True, db_column='id_desconto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='senhorio.desconto')),
            ],
            options={
                'db_table': 'estudante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_estudante', models.OneToOneField(db_column='id_estudante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='estudante.estudante')),
                ('curso', models.IntegerField()),
                ('anolectivo', models.CharField(max_length=255)),
                ('uc', models.CharField(max_length=255)),
                ('classificacao', models.IntegerField(blank=True, null=True)),
                ('id_desconto', models.ForeignKey(db_column='id_desconto', on_delete=django.db.models.deletion.DO_NOTHING, to='senhorio.desconto')),
            ],
            options={
                'db_table': 'nota',
                'managed': True,
                'unique_together': {('id_estudante', 'curso', 'anolectivo', 'uc')},
            },
        ),
    ]
