# Generated by Django 5.0.3 on 2024-03-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudante', '0001_initial'),
        ('senhorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamento',
            fields=[
                ('id_alojamento', models.AutoField(primary_key=True, serialize=False)),
                ('renda_base', models.FloatField(db_column='renda_base')),
                ('nquartos', models.IntegerField()),
                ('aluguerparcial', models.CharField(max_length=255)),
                ('nquartoslivres', models.IntegerField()),
                ('id_senhorio', models.ForeignKey(db_column='id_senhorio', on_delete=django.db.models.deletion.DO_NOTHING, to='senhorio.senhorio')),
            ],
            options={
                'db_table': 'alojamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aluguer',
            fields=[
                ('id_estudante', models.OneToOneField(db_column='id_estudante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='estudante.estudante')),
                ('id_senhorio', models.IntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('renda_final', models.IntegerField(db_column='renda_final')),
                ('id_alojamento', models.ForeignKey(db_column='id_alojamento', on_delete=django.db.models.deletion.DO_NOTHING, to='alojamento.alojamento')),
            ],
            options={
                'db_table': 'aluguer',
                'managed': True,
                'unique_together': {('id_estudante', 'id_senhorio', 'id_alojamento', 'data_inicio')},
            },
        ),
    ]
