# Generated by Django 5.0.3 on 2024-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id_desconto', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'desconto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Senhorio',
            fields=[
                ('id_senhorio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'senhorio',
                'managed': False,
            },
        ),
    ]
