# Generated by Django 5.0.3 on 2024-03-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id_prestador', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prestador',
                'managed': True,
                'unique_together': {('id_prestador', 'id_tipo')},
            },
        ),
        migrations.CreateModel(
            name='ContratoServ',
            fields=[
                ('id_senhorio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo', models.IntegerField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('mensalidade', models.IntegerField()),
                ('id_alojamento', models.ForeignKey(db_column='id_alojamento', on_delete=django.db.models.deletion.DO_NOTHING, to='alojamento.alojamento')),
                ('id_prestador', models.ForeignKey(db_column='id_prestador', on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.prestador')),
            ],
            options={
                'db_table': 'contrato_serv',
                'managed': True,
                'unique_together': {('id_senhorio', 'id_prestador', 'id_tipo', 'id_alojamento')},
            },
        ),
    ]
